### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by RobertCordes** [ryangjchandler/alpine-tooltip#1]
Hi, when trying to install the plugin as per the docs, I was getting the following error using Laravel Mix (Webpack):

```
Module not found: Error: Can't resolve '@ryangjchandler/alpine-tooltip' in …
```

I fixed it by editing your package.json directly, changing `"main": "dist/alpine-tooltip.cjs.js"` to `"main": "dist/module.cjs.js"` and `"module": "dist/alpine-tooltip.esm.js"` to `"main": "dist/module.esm.js"`.

I would create a PR, but unfortunately, I have no idea to do this properly. 😅 Also, maybe I was just doing something wrong in the first place. Anyways, I hope this will help someone else.

**Comment by ryangjchandler** [comment]
Ah, rookie error on my part. I'll get this fixed & a new release tagged - thanks @RobertCordes!

**Comment by ryangjchandler** [comment]
Closed by https://github.com/ryangjchandler/alpine-tooltip/commit/d5cb1b09381df2af9cc47d452d910bad2b6a015a

**Comment by ryangjchandler** [comment]
@RobertCordes Please upgrade to v0.1.2 which has the correct entrypoints.

**Comment by RobertCordes** [comment]
Just did. Thanks for the fix!
