### ISSUE TITLE
How to use multiple modifiers simultaneously?

### ISSUE THREAD

**Issue by felixhtoo30** [ryangjchandler/alpine-tooltip#15]
I would like to use `x-tooltip` like this:

`
<span x-tooltip.on.click="tooltip" x-tooltip.placement.left>
   <i class="icon-question-circle1"></i>
</span>
`
I want it to appear left placement when click event (not default hovering). But, click event only works, and left placement not working (i.e. appearing on top - default placement).

Any help, plz.

**Comment by ryangjchandler** [comment]
@felixhtoo30 You can chain the modifiers together, e.g.

```html
<span x-tooltip.on.click.placement.left="tooltip">
```

The argument for the modifier must follow the modifier directly, something like `.on.placement.left.click` won't work, it has to be `.on.click.placement.left`.

**Comment by felixhtoo30** [comment]
> @felixhtoo30 You can chain the modifiers together, e.g.
> 
> ```
> <span x-tooltip.on.click.placement.left="tooltip">
> ```
> 
> The argument for the modifier must follow the modifier directly, something like `.on.placement.left.click` won't work, it has to be `.on.click.placement.left`.

It works like a charm! Thank you.
