### ISSUE TITLE
tooltip doesn't work when you add disable to button

### ISSUE THREAD

**Issue by SurfJunky** [ryangjchandler/alpine-tooltip#16]
as the title says 

here is an example 
```
<div x-data="{ tooltip: 'This is crazy!' }">
        <button disabled x-tooltip="tooltip">Hover for info!</button>
</div>
```
    
Thank you :)

**Comment by ryangjchandler** [comment]
I believe disabling a button will prevent certain events from being fired which Tippy is listening too. It's not necessarily a bug, so I'm going to close this issue. I'd recommend either working around the problem but not using a button at all, or instead disabling by preventing pointer events or something.
