### ISSUE TITLE
Html content

### ISSUE THREAD

**Issue by dgironella** [ryangjchandler/alpine-tooltip#19]
Activate allow html not working. Html not parsed.

`<div x-data="{pdata:'<strong>hola</strong>'}">
        <button x-tooltip="pdata" x-tooltip.html>Hover me</button>
    </div>`

**Comment by ryangjchandler** [comment]
You should only have a single `x-tooltip` directive on your element. Please add the `.html` modifier to the first directive instead.

**Comment by dgironella** [comment]
yes, this work thanks.
