### ISSUE TITLE
Add `$tooltip` magic variable

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/alpine-tooltip#20]
At the moment, tooltips can only be created with the `x-tooltip` directive. Would be pretty neat if we had a `$tooltip` directive that could show them on-demand.

```js
<button @click="$tooltip('Hello, world!', { /* tippy config object */ })">
```

**Comment by simonbuehler** [comment]
does the `$tooltip` config object accept `onUntrigger` so we can do stuff like setting alpine vars etc when the tooltip get hidden ?

**Comment by ryangjchandler** [comment]
The config object is just a plain object that accepts all config values that Tippy does, so in theory if that's possible with Tippy, it should be possible with `$tooltip` yeah.
