### ISSUE TITLE
change background to white 

### ISSUE THREAD

**Issue by BenOussama180** [ryangjchandler/alpine-tooltip#31]
how can i change tooltip background to white  ?

**Comment by ryangjchandler** [comment]
Please look at the Tippy.js for information regarding themes.

**Comment by BenOussama180** [comment]
@ryangjchandler should i npm install tippy to import theme styles or is it already installead with alpine tooltip ?

**Comment by ArtMin96** [comment]
@BenOussama180 try this

```javascript
import "tippy.js/themes/light.css";

//...
allowHtml: true,
theme: 'light',
//...
```
