### ISSUE TITLE
The tooltip does not appear

### ISSUE THREAD

**Issue by HosMercury** [ryangjchandler/alpine-tooltip#32]
```
     <button class="border inline text-black p-1 bg-white rounded m-1"
      x-text="product.number" x-tooltip="product.name"></button>
```
                                                
  I have added the script and the CSS but the tooltip not show , Even the raw tooltip does not show .. nothing works
  
```
      <link rel="stylesheet" href="//unpkg.com/tippy.js@6/dist/tippy.css" />
    <script src="//cdn.jsdelivr.net/npm/@ryangjchandler/alpine-tooltip@1.x.x/dist/cdn.min.js" defer></script>
```

**Comment by ryangjchandler** [comment]
@HosMercury You'll need to provide more information. Do you get any console errors?

**Comment by HosMercury** [comment]
no errors

**Comment by ryangjchandler** [comment]
Is the button inside of an Alpine component? Is the button text working?

**Comment by HosMercury** [comment]
Yes the text works perfectly

**Comment by timothyis** [comment]
I just ran into an issue where `x-tooltip.raw` didn't show without an empty `x-data` on the same element (didn't test a parent), but perhaps it's not finding the data?

I don't think the `raw` modifier is meant to require `x-data` though, right @ryangjchandler?

**Comment by ryangjchandler** [comment]
@timothyis `x-data` is required, since that is what evaluates Alpine directives.

**Comment by ryangjchandler** [comment]
I wouldn't say so. The package is an Alpine plugin and therefore implies that you're using it inside of an Alpine component? If you want to update that, feel free to send a PR!
