### ISSUE TITLE
Define theme globally

### ISSUE THREAD

**Issue by undjike** [ryangjchandler/alpine-tooltip#36]
Hello Team,

Does anyone know how to set the tooltip theme globally ?
I'm aware one can change theming per tooltip, but I don't want to be specifying the theme for each and every tooltip.

**Comment by ryangjchandler** [comment]
@undjike From what I can see in Tippy's documentation, there isn't a way to set the theme globally, it can only be done per tooltip. I might be able to add something in the plugin to support setting the theme globally.

**Comment by undjike** [comment]
> From what I can see in Tippy's documentation, there isn't a way to set the theme globally, it can only be done per tooltip.

I thought this code found in the [Tippy's doc](https://atomiks.github.io/tippyjs/v6/customization/#default-props)  aimed to do that.

```js
tippy.setDefaultProps({delay: 50});
```

> I might be able to add something in the plugin to support setting the theme globally.

That will be great please.

**Comment by ryangjchandler** [comment]
Since Tippy is bundled with the plugin, there will need to be some way of doing it through the plugin's API. I can put together a quick PR right now :)

**Comment by undjike** [comment]
Marvellous. 👍

**Comment by ryangjchandler** [comment]
@undjike Update to `v1.3.0` and follow instructions inside of README: https://github.com/ryangjchandler/alpine-tooltip#setting-default-tippy-properties

**Comment by undjike** [comment]
Great 🤗

**Comment by undjike** [comment]
It works like a charm. 👍

**Comment by dgknca** [comment]
how to do this without using module?
