### ISSUE TITLE
Viewport overflow issues

### ISSUE THREAD

**Issue by marttheis** [ryangjchandler/alpine-tooltip#41]
Hi,

The content of the tooltip breaks and wraps correctly in order to stay within the viewport. However the actual box overflows the viewport  if zoomed in or on mobile.  You can see on the screenshot that the x-scrollbar appears once the tooltip is shown and that the box does not stay within the viewport on the right side.

How can I modify this? How can I add css to make to render correctly?

best regards
Martin

![Alpine tooltip overflow](https://github.com/ryangjchandler/alpine-tooltip/assets/114695786/50976895-5e1a-444a-9d74-37c3a590bb62)

**Comment by ryangjchandler** [comment]
@marttheis The plugin uses Tippy so you can just write your own CSS. If you inspect the element in the DOM, you'll be able to see the classes, otherwise consult the Tippy documentation directly.

**Comment by marttheis** [comment]
Thank you for the instant support Ryan. Great plugin and now it works like a charm.

**Comment by ryangjchandler** [comment]
Thanks @marttheis, appreciate it!
