### ISSUE TITLE
Example not working following your instructions

### ISSUE THREAD

**Issue by christoferd** [ryangjchandler/alpine-tooltip#45]
Hi, Any ideas on how to resolve this?

Example not working following your instructions
- loading Alpine JS via CDN
- using the CDN

https://jsfiddle.net/q102fh8c/11/

Tried it with Tailwind and without.

Could this have something to do with the latest version of Alpine JS?

**Comment by ryangjchandler** [comment]
As per the instructions, the CDN script needs to be placed before the Alpine.js script.

**Comment by christoferd** [comment]
Okay, thanks, working now in this example.

https://jsfiddle.net/z4u13fjb/8/
