### ISSUE TITLE
Is there any way to use trigger: 'mouseenter click' ?

### ISSUE THREAD

**Issue by jskorlol** [ryangjchandler/alpine-tooltip#7]
I need to keep the tooltip on mouseover and click... but there is currently no way to do it ?

**Comment by ryangjchandler** [comment]
We only support one event at the moment using the `.on.mouseenter` modifier combination. 

Let me think of a potential way to support multiple events.

**Comment by jskorlol** [comment]
Okay, thank you as always !
Have a nice day !
